### ISSUE TITLE
Don't exit process when single-run

### ISSUE THREAD

**Issue by petebacondarwin** [karma-runner/gulp-karma#3]
I am pretty sure that karma will exit when it finishes a single run task.
Assuming this is the case, we should not be calling `process.exit()` when the single run has completed. This would prevent any subsequent tasks from being run.

Instead we should make use of Gulp's async task support.  You can get a done method from the task parameter list:

```
gulp.task('test', function (done) {
  karma.start(_.assign({}, karmaCommonConf, {singleRun: true}), done);
});
```

Have you tried this?  Is there something funny about the karma server that doesn't exit cleanly?

**Comment by zellwk** [comment]
I have a problem here as well. I noticed that the process doesn't exit whenever I use jquery in my files: 

here's the trace: 

```
Firefox 36.0.0 (Mac OS X 10.10.0): Executed 4 of 4 SUCCESS (0.003 secs / 0.001 secs)
[14:12:46] Finished 'test' after 1.21 s

25 08 2015 14:12:56.838:WARN [Firefox 36.0.0 (Mac OS X 10.10.0)]: Disconnected (Firefox 36.0.0 (Mac OS X 10.10.0): Executed 4 of 4 DISCONNECTED (10.005 secs / 0.001 secs)
[14:12:56] 'test' errored after 11 s
[14:12:56] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/zellwk/Projects/Automating Your Workflow/project/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/zellwk/Projects/Automating Your Workflow/project/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/zellwk/Projects/Automating Your Workflow/project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/zellwk/Projects/Automating Your Workflow/project/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/zellwk/Projects/Automating Your Workflow/project/node_modules/karma/lib/server.js:325:7)
    at /Users/zellwk/Projects/Automating Your Workflow/project/node_modules/karma/lib/server.js:336:9
    at Server.<anonymous> (net.js:1376:9)
    at Server.g (events.js:199:16)
    at Server.emit (events.js:104:17)
    at net.js:1419:10
    at process._tickCallback (node.js:355:11)
```

Any ideas?

**Comment by zellwk** [comment]
My bad. Just realized this: You can't have console.log statements in your files, otherwise the above error will happen.

**Comment by hrajchert** [comment]
I don't think this issue is resolved. I have a publish task in my gulpfile and before I do that I want to run the unit test, but 2 seconds after they run, my process die :(.

Why does karma need to do a process.exit() if not in singlerun?

**Comment by johannesjo** [comment]
I'm still having the same issue. This is not resolved.

**Comment by lazd** [comment]
~~This module is deprecated.~~

@johannesjo Ah, sorry. Maybe there was a regression? I remember noting this was fixed when testing myself.

**Comment by johannesjo** [comment]
I mean this issue still stands when using karma directly as provided by the example.

**Comment by johannesjo** [comment]
This is possibly a duplicate of https://github.com/karma-runner/karma/issues/1788

**Comment by gandra** [comment]
Having the same issue with fresh new angular2 app made with angular cli: http://stackoverflow.com/questions/42030568/how-to-manage-to-exit-phantomjs-launcher-after-tests-execution

**Comment by ovod88** [comment]
Hello.
I have the same issue. Is it resolved?

**Comment by Jeff-Tian** [comment]
Bump

**Comment by johnjbarton** [comment]
This issue is old and closed. Please open a new one with recent version and fresh information.
